---
# Same as dev.aws_ec2.yml but scoped to the prod instances.
plugin: amazon.aws.aws_ec2
filters:
  tag:Project: demo-app
  tag:Env: prod
  instance-state-name: running
hostnames:
  - instance-id
keyed_groups:
  - key: ec2_tags.Role
    prefix: ""
    separator: ""
compose:
  ansible_host: public_ip_address
  private_ip: private_ip_address
